export { default as Home } from './Home'
export { default as About } from './About'
export { default as TypeSite } from './TypeSite'
export { default as Services } from './Services'
export { default as SubService } from './SubService'
